.travis.yml
src/dgemm_kernel.rs
src/gemm.rs
src/kernel.rs
src/sgemm_kernel.rs
tests/sgemm.rs

- Add an element trait to access the one, zero elements of f32, f64 and so on.
- Then break out the masked kernel logic to make it a general implementation
(However we cheat, to use an array on the stack for now, with the correct size. Can be fixed when
we get more than 4x4 kernels. I did check that the complied code is the same when using a vector there as an array.)
- I noticed that masked_kernel had its own codegen of the gemm kernel, and that it produced better code! It was using wide AVX registers (ymm1, ymm2 etc) instead of just the xmm1 registers. I don't really understand why this happens. So.. if I change all kernel use to go through masked_kernel, performance improves!
-  First difference is that masked_kernel writes into a local buffer, with known row/col stride. After that it …

A faster multiplication with more ymm1; Also make the mask kernel more generic

---

.travis.yml
src/dgemm_kernel.rs
src/gemm.rs
src/kernel.rs
src/loopmacros.rs
src/sgemm_kernel.rs

Support aligned buffers in preparation for plugging in better vectorized solutions that need it.
It turns out dgemm improves with a 8-by-4 µ-kernel (instead of 4-by-4) when AVX is available, so we use it.
Benchmark report says it improves throughput up to 18% with -target-cpu=native with AVX, but regresses by 16% by with default release mode settings on the same platform. We will choose to merge this to shoot for the best possible performance.
```
name                           4x4-dgemm.log ns/iter  8x4-dgemm.log ns/iter    diff ns/iter   diff %
mat_mul_f64::m016              1,254                  1,103                            -151  -12.04%
mat_mul_f64::m064              47,573                 38,887                         -8,686  -18.26%
mat_mul_f64::m127              344,298 …
```

Non-square µ-kernels, aligned buffers and a 8-by-4 kernel for dgemm

---

Cargo.toml
README.rst
benches/bench1.rs
docs/sgemm4x4.log
docs/sgemm4x8.log
src/dgemm_kernel.rs
src/loopmacros.rs
src/sgemm_kernel.rs

Use a 4-by-8 microkernel for sgemm
Processing more data per kernel is a win. Some small sizes that need
more zero padding regress by a few percent.
```
name                           sgemm4x4.log ns/iter  sgemm4x8.log ns/iter    diff ns/iter   diff %
mat_mul_f32::m004              153                   172                               19   12.42%
mat_mul_f32::m007              280                   271                               -9   -3.21%
mat_mul_f32::m008              305                   286                              -19   -6.23%
mat_mul_f32::m012              598                   650                               52    8.70%
mat_mul_f32::m016              1,044                 945                              -99   -9.48%
mat_mul_f32::m032              5,037 …
```

Use a 4-by-8 microkernel for sgemm

---

src/dgemm_kernel.rs
src/sgemm_kernel.rs

This works around the performance regression on nightly (LLVM 3.9 + MIR trans), which was related to the failing removal of array initialization expressions like `[0.; 4]`. Using `zeroed` works arounds this. (Thank you @eddyb!)
Fixes #9 (by working around it)

Use mem::zeroed to fill the gemm kernel's array for the vectors

---

src/dgemm_kernel.rs
src/loopmacros.rs
src/sgemm_kernel.rs

-C target-cpu=native
```
name               sgemm-4x8-before.log ns/iter  sgemm-4x8-unroll5.log ns/iter    diff ns/iter   diff %
mat_mul_f32::m004  132                           109                                       -23  -17.42%
mat_mul_f32::m005  205                           151                                       -54  -26.34%
mat_mul_f32::m006  229                           166                                       -63  -27.51%
mat_mul_f32::m007  250                           182                                       -68  -27.20%
mat_mul_f32::m008  219                           200                                       -19   -8.68%
mat_mul_f32::m009  465                           377                                       -88  -18.92%
mat_mul_f32::m012  628 …
```

Improve unrolling in sgemm kernel

---

.travis.yml
Cargo.toml
build.rs
src/loopmacros.rs
src/sgemm_kernel.rs

In sgemm (f32) use 8x8 kernel if AVX is enabled. (This is open to more platform specific tuning).
Improvement from sgemm 4x8 to 8x8 with avx:
```
name                     old-f32 ns/iter  new-f32 ns/iter  diff ns/iter   diff % 
mat_mul_f32::m004        110              103                        -7   -6.36% 
mat_mul_f32::m005        162              117                       -45  -27.78% 
mat_mul_f32::m006        170              136                       -34  -20.00% 
mat_mul_f32::m007        191              148                       -43  -22.51% 
mat_mul_f32::m008        211              163                       -48  -22.75% 
mat_mul_f32::m009        371              346                       -25   -6.74% 
mat_mul_f32::m012        484              461                       -23 …
```

Use CARGO_CFG_TARGET_FEATURE to pick sgemm 8x8 if avx exists

---

src/gemm.rs

A stride is irrelevant if the length of its axis is ≤ 1 or if the length of the other axis is 0, since its value is never used in an offset. (There may be an offset of `0 * stride` if the length of the axis is 1, but 0 times anything is zero, so the stride is irrelevant.)

Relax debug assertion on strides of C matrix

---

src/sgemm_kernel.rs

The sgemm avx kernel preferred A B → C with C row major by default, but if
C is column major (and not row major, or a custom strided layout), we
can simply compute the transpose B<sup>T</sup> A<sup>T</sup> → C<sup>T</sup> instead.
This removes the row major bias in the layout benchmarks (sgemm avx), and we are
equally fast on f and c outputs:
(The notation we use is "c" for row major and "f" for column major.
For example "fcf" means that A is column major, B is row major, C is column major in matrix mult A B → C)
```
name                 63 ns/iter  62 ns/iter  diff ns/iter   diff %
layout_f32_032::ccc  2,032       2,033                  1    0.05%
layout_f32_032::ccf  2,279       2,026               -253  -11.10%
layout_f32_032::cfc  2,275       2,291                 16    0.70% …
```

In the sgemm avx kernel, transpose if we can match C's layout

---

Cargo.toml
src/dgemm_kernel.rs

This is a first working version of the dgemm kernel using avx intrinsics. I cannot yet see a difference between the autovectorized version and this one. Bit of a bummer.
Todo:

Implement DGEMM kernel using avx intrinsics

---

.travis.yml
src/dgemm_kernel.rs
src/sgemm_kernel.rs

This uses fused multiply add via `_mm256_fmadd_{ps,pd}` to multiply and accumulate matrices in one go. The performance gains are impressive, as described in issue #35.
Fixes #31 
Fixes #35 
Fixes #38

Implement sgemm and dgemm using fma

---

.travis.yml
src/dgemm_kernel.rs
src/gemm.rs
src/kernel.rs
src/loopmacros.rs
src/sgemm_kernel.rs

Allow separate GemmKernel implementations per feature, so that we can tweak kernel parameters per feature. This also allows us to restore the performance of the fallback kernels.
We introduce a selector trait and when entering for example `sgemm`, we pass control to `sgemm_kernel::detect`, and it selects which kernel implementation to use. Control passes back to the gemm module and it launches the `gemm_loop` using the selected kernel.
This approach allows us to insert a cache (ifunc strategy #23) in the gemm module if we want to cache the function pointer to avoid running detection many times. But it's unlikely that we are going to need that.
This is also an improvement since we don't need to run detection every kernel invocation! Repeated detection is just an atomic load and compare, so …

More flexible kernel selection

---

src/dgemm_kernel.rs
src/gemm.rs
src/kernel.rs
src/sgemm_kernel.rs

The multiplication by `alpha` should be performed by the actual kernel. This leaves the masked kernel loop to only do addition when constructing the C matrix.
Looks like there is a reliable gain for `f64` double precision of about 3-4% on my system (`avx` and `fma` enabled) at no cost:
```
name                 with_scale_add ns/iter  no_scale_add ns/iter  diff ns/iter  diff %  speedup 
layout_f32_032::ccc  1,765                   1,751                          -14  -0.79%   x 1.01 
layout_f32_032::ccf  1,754                   1,762                            8   0.46%   x 1.00 
layout_f32_032::cfc  2,019                   2,026                            7   0.35%   x 1.00 
layout_f32_032::cff  2,030                   2,032                            2   0.10%   x 1.00 …
```

Only add in masked kernel loop

---

src/gemm.rs
src/kernel.rs

- Instead of setting "c = 0; c += ab", use `c = ab` directly
- Try to resolve some of the aliasing problems
Functions where we have multiple raw pointers often have the compiler confused about aliasing. In this case, `*cptr *= beta; *cptr += *ab;` had it compile to *2* reads of the value in `*cptr` when one would be enough. We could explicitly write the read value, operate, store back, but here we tried instead to insert a function that takes the `mask_buf` pointer as a shared reference (and those are marked noalias). This is a workaround that sometimes works..
Fallback kernel benchmark improvement:
```
name               63 ns/iter  62 ns/iter  diff ns/iter  diff % 
mat_mul_f32::m032  3,624       3,393               -231  -6.37% 
mat_mul_f64::m032  6,410       6,110               -300 …
```

Minor changes to kernel masking

---

Cargo.toml

This is the latest version and syncs with the version ndarray will be using in the next release.

Update rawpointer dependency to 0.2

---

.travis.yml
Cargo.toml
benches/benchmarks.rs
blas-bench/benches/benchmarks.rs
ensure_no_std/.gitignore
ensure_no_std/Cargo.toml
ensure_no_std/src/main.rs
examples/usegemm.rs
src/aligned_alloc.rs
src/dgemm_kernel.rs
src/gemm.rs
src/kernel.rs
src/lib.rs
src/sgemm_kernel.rs
src/util.rs
src/x86/macros.rs
src/x86/mod.rs
tests/sgemm.rs

This is the follow-up to #46. I fixed the build issue with the benchmark trying to use core when it is using std. I also added CI tests for no_std. If CI fails, I will make additional changes. I have not previously used Travis CI, so I don't know if what I wrote will work, but that is what CI is for :smiley:.
Closes #46

no_std support

---

.github/workflows/ci.yml
examples/benchmark.rs

This binary takes command line arguments to set the size of matrix multiplication problem to benchmark.

Add benchmark runner as an "example" binary

---

.github/workflows/ci.yml
Cargo.toml
benches/benchmarks.rs
examples/benchmark.rs
src/aligned_alloc.rs
src/dgemm_kernel.rs
src/gemm.rs
src/lib.rs
src/loopmacros.rs
src/ptr.rs
src/sgemm_kernel.rs
src/threading.rs
src/util.rs
src/x86/mod.rs

Use a tree-structured thread pool and introduce a "minimum viable product" implementation of multithreading.
The tree structure thread pool allows us to get around the slowdown from worker contention that we have seen in other solutions (in experiments with rayon and other thread pools).
More or less, other thread pools show some overhead due to contention when delivering work items to the pool, for example when having a too small matrix with just two work items, the four pools in the thread pool would use extra cpu time just looking for work. The tree structure thread pool avoids this.
Now we instead have this structure:
```rust
// Every node has two fields:
// - sender: A channel sender to pass jobs to its right child
// - child: An array of the two child nodes.
//
// The root node has …
```

Add threading support

---

src/gemm.rs

New in 0.3.0 was that we are using TLS for the masking buffer,
and using `#[repr(align(32))]` to 32-byte align it. It seems one
of those choices didn't work out.
So we manually align the pointer into the buffer anyway, due to
bugs we have seen on certain platforms (macos) that look like
we don't get aligned allocations out of TLS (?).
Fixes #55 (Hopefully)
This removes the debug assertion we are hitting in #55, because
here we make the alignment happen.
Halfway reverts previous commit 2ddd0ba04b8ff0f2f82fd3cf6459955fdd536be5

Align mask buffer pointer manually

---

.github/workflows/ci.yml
Cargo.toml
README.rst
examples/benchmark.rs
src/archparam.rs
src/cgemm_common.rs
src/cgemm_kernel.rs
src/dgemm_kernel.rs
src/gemm.rs
src/kernel.rs
src/lib.rs
src/loopmacros.rs
src/sgemm_kernel.rs
src/threading.rs
src/zgemm_kernel.rs
testdefs/testdefs.rs
tests/sgemm.rs

Use the feature name "cgemm" for cgemm/zgemm methods; start them
off by adding fallback implementations using 4x2 kernels.
CGemmOptions added as a placeholder - can later include options for
conjugating either operand (transpose not required - the strides provide
that freedom already).
Extensive updates for benchmarks, a simple argument parser
makes it easier to use.
Better testing, refactoring some common code and better test coverage.
Complex is using the representation [f64; 2] here which is
representation compatible in memory with C and with num_complex.

Add experimental support for complex: cgemm/zgemm

---

Cargo.toml
LICENSE-MIT
src/archparam.rs
src/archparam_defaults.rs
src/constparse.rs
src/lib.rs
src/zgemm_kernel.rs

This introduces compile-time tweak environment variables like this:
- MATMUL_DGEMM_NC
- MATMUL_DGEMM_MC
- MATMUL_DGEMM_KC
etc for each gemm. These allow setting these size parameters at
compile time - they should ideally be optimized per kernel *and
microarch*.
Combine these parameters with the benchmark in ./examples/benchmark.rs
and its csv output option - this allows optimizing performance depending
on these parameters. This was already useful for complex.
Using DutchGhost's const parsing code from
https://gist.github.com/DutchGhost/d8604a3c796479777fe9f5e25d855cfd
which has been very useful.
Co-authored-by: DutchGhost <DutchGhost@users.noreply.github.com>

Allow tweaking size parameters at compile time

---

.github/workflows/ci.yml
ci/miri.sh
tests/sgemm.rs

- Threading is supported in miri, except the num_cpus::get_physical call, which is skipped
- Miri is extremely slow at running the full unoptimized gemm loop unfortunately, any non-trivial matrix sizes are skipped in tests (which is a shame, there are more branches to cover for larger sizes).

Run miri in the testuite

---

src/constparse.rs

There was an overflow in the pow10 table on 32-bit arches, try to fix
this.

Fix usize parsing on 32-bit arch

---

src/ptr.rs

Add a "definitely non-Send/Sync" field to Ptr so that the explicit
Send/Sync impls become unambiguous to the compiler.
This fixes the warning from rust-lang/rust#93367

Fix Send/Sync impls for future compat warning

---

ci/miri.sh
src/gemm.rs

Before this PR, running `MIRIFLAGS="-Zmiri-tag-raw-pointers" cargo miri test` caused Miri to report undefined behavior in the `test_dgemm` test. This PR fixes the underlying issue – Miri doesn't like us using a reference to an element to access other elements.
There may be other Miri errors. Miri takes forever to run, and I haven't waited for it to finish yet.

Fix Miri error with -Zmiri-tag-raw-pointers

---

src/dgemm_kernel.rs

While looking through the code I noticed that a comment describing why certain permutations are done a certain way with intrinsics did not reflect what was actually done in the code. Specifically the permutation set mentioned in the comment was 
{0123, 1032, 2301, 3012} while the actual permutations are {0123, 1032, 3210, 2301}.
In addition the comment mentioned alternative selections that were partly not correct with respect to what the code was actually doing. I updated them and verified the correctness according to [the intel docs](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#ig_expand=6418,5227&techs=AVX,AVX2&cats=Swizzle) as well as [tests on godbolt](https://godbolt.org/z/xn8cWdx38).

Updated comment in function kernel_x86_avx

---

src/ptr.rs

Revisit the previous fix. It's clear that the Ptr code will not change
meaning with the coming breaking change, because it's only ever used
with Ptr<*const T> and Ptr<*mut T> as parameterizations.
For this reason, it's more correct IMO to accept the code meaning
change, which doesn't change the meaning of the crate, by silencing the
warning and not making any unnecessary and ugly changes to the struct
fields.

Silence suspicious Send/Sync impls warning

---

src/gemm.rs

As a second fix for the TLS on macos alignment problem, request only 16-byte alignment on macos, because we don't get more.
There's a new debug assertion in std which trips on accessing otherwise, even if it does not really affect us.
Fixes #55 (hopefully)

Request only 16-byte alignment on macos

---

src/gemm.rs

Using a reference type (such as a slice) for either pack or a in the packing
function makes rustc emit a noalias annotation for that pointer, and that helps
the optimizer in some cases.
What we want is that the compiler sees that the pointers pack and a and
pointers derived from them, can never alias, then it has more freedom to
rewrite the operations in the packing loops.  The pack buffer is contiguous so
it's the only choice for passing one of the two arguments as a slice.
Shown to slightly speed up the layout benchmarks for sgemm, not dgemm, on
M1. No effect noticed on x86-64.
A way to get the same effect without a slice would be good for this crate,
like a 'restrict' keyword.

Use slice in packing function for noalias optimization

---

.github/workflows/ci.yml
Cargo.toml
benches/benchmarks.rs
build.rs
spare kernels/aarch64_neon_4x4.rs
src/aarch64/macros.rs
src/aarch64/mod.rs
src/archmacros.rs
src/dgemm_kernel.rs
src/kernel.rs
src/lib.rs
src/loopmacros.rs
src/sgemm_kernel.rs
src/threading.rs
tests/sgemm.rs

Implement
* 8x8 sgemm kernel for AArch64 using NEON instructions
* 8x4 dgemm kernel for AArch64 using NEON instructions
**Benchmarks (single thread)**
Using benches/benchloop.py in the repository.
on Apple Silicon M1 (MacBookAir10,1 3.2 GHz) 
* sgemm 96.4 gflop/s at M,N,K = 1024
* dgemm 45.8 gflop/s at M,N,K = 1024
Not revolutionary, comparable (for sgemm) with openblas. (Apple Accelerate uses other proprietary extensions which are miles ahead.)
AArch64 NEON has 32 registers, each 128-bit, corresponding being able to store 128 x f32 or 64 x f64. To keep the whole kernel in memory, the upper limit of kernel size would be somewhere below 16x8 for f32.
Further kernel size and NC, KC, MC tweaks can give further benefits here (less significant compared to the already won performance), this PR …

Arm64/AArch64 Neon kernels

---

.github/workflows/ci.yml
ci/miri.sh
src/cgemm_common.rs
src/cgemm_kernel.rs
src/dgemm_kernel.rs
src/gemm.rs
src/kernel.rs
src/lib.rs
src/packing.rs
src/sgemm_kernel.rs
src/zgemm_kernel.rs
testdefs/testdefs.rs
tests/sgemm.rs

**Complex (cgemm, zgemm):**
Use a different pack layout for complex micorkernels which puts real and
imag parts in separate rows. This enables much better autovectorization for
the fallback kernels.
Also enable an Avx2 + Fma autovectorized kernel.
Performance improvements (all kernels autovectorized for cgemm, zgemm
at this time)
- AArch64 NEON (apple m1): cgemm: +60%, zgemm +10% 
- Fma + Avx (Intel Tiger lake) cgemm: +143%
- Fma + Avx2 (Intel Tiger lake) cgemm: +395% (new),  zgemm: +77% (new)
**Float (sgemm, dgemm):**
When the kernels can now select their own packing functions, instantiate
an avx2 version of the general packing function for sgemm and dgemm.
Packing performance matters most for small matrix multiplications, for
bigger sizes it is a vanishingly small part of runtime.
- …

Special packing for complex, specialize packing for avx2

---

ensure_no_std/Cargo.toml
src/cgemm_common.rs

cgemm was not tested as nostd in ci
Fixes #76

Fix nostd build for complex

---

.github/workflows/ci.yml
src/gemm.rs

A user showed that in certain configurations, the TLS allocation can even be 8-byte aligned.
Fixes rust-ndarray/ndarray#1327

request 8-byte buffer alignment on macos

---

.github/workflows/ci.yml
src/gemm.rs

Requested 32-alignment for s390x but thread local storage does not
supply it. Lower requested align to 16 in general to avoid having this
problem pop up on other platforms too.
Dynamic code downstream updates alignment to kernel's requested alignment, which can be larger than the base (static) alignment request.

Fix alignment in s390x and cross test

---

src/gemm.rs

Windows 7 does not respect 16 byte alignment for thread locals on i686
builds. Rust 1.79 changed i686 windows builds to use native thread local
support. As a result, using `matrixmultiply` on i686 win7 builds leads
to a UB check panic nounwind when run on Windows 7. See
<https://github.com/rust-lang/rust/issues/138903> for more info.
This change adds `i686-win7-windows-msvc` as an excluded target for the
alignment attribute on `MaskBuffer`.
Not sure how you feel about adding this exclusion in `matrixmultiply` as its
very much for a tier 3 target that you can't test in CI that its useful. But
figured I'd raise it, as it would affect users using that target on any recent
toolchain version. And fwiw, i did test that this does in fact have the desire
for compilations targeting i686-win7

Exclude alignment for MaskBuffer for i686-win7-windows-msvc

---

src/sgemm_kernel.rs

- Removed redundant `_mm256_permute2f128_ps` instructions for lane swapping.
- Reordered final output assignments to match the expected layout directly, simplifying downstream processing.
- This change reduces register pressure and improves instruction efficiency without altering the computation logic.
**Tested on Intel 10700k (Single core)**  
| Matrix Size | Before Optimization (ns/iter) | After Optimization (ns/iter) | Improvement (%) |
|--------------|-------------------------------|------------------------------|-----------------|
| m004        | 177 (+/- 1)                  | 174 (+/- 17)                | **1.69%**      |
| m006        | 209 (+/- 19)                 | 202 (+/- 20)                | **3.35%**      |
| m008        | 200 (+/- 0)                  | 191 (+/- 1) …

sgemm: Reduce unnecessary AVX register permutations
